### ISSUE TITLE
Gestures problem

### ISSUE THREAD

**Issue by som-num** [closebox73/applying-theme#13]
I am using Arch linux running in gnome 44 and just installed the nashira-Dark theme. So the issue is that when I switch to another desktop using gestures the conky would appear 
![image](https://github.com/closebox73/applying-theme/assets/78010819/ec05e563-4835-4d59-9c87-672633413d5c)
however when I arrive at the desktop it disappears
![image](https://github.com/closebox73/applying-theme/assets/78010819/b87dcaac-904b-41db-b175-7b19f5ee24d7)
I don't know if it is an issue with the theme or the conky itself. sorry I am still new to linux and just exploring tnx

**Comment by closebox73** [comment]
@som-num another desktop?  you mean workspaces?

**Comment by som-num** [comment]
@closebox73 ohh so that's what they're called thanks. but yeah it glitches out when I switch workspaces when I use gestures but it doesnt glitch out when I don't use gestures

**Comment by som-num** [comment]
It is an honor to be noticed by the creator of this rice. Thank you for creating this masterpiece, and yeah I found it on unixporn but never expected to meet you here lmao. I turned off my blur my shell extension and it absolutely worked! Thank you again for this tip. Please keep creating these magnificent rice🫶

**Comment by closebox73** [comment]
@Noob-linux-user Your is Noob, but you're actually not a noob at all🤔

**Comment by Noob-linux-user** [comment]
glad I could help you :) 

@closebox73  haha i am just learning this and that from here and there, i faced the same problem myself before. you can close this issue now i guess
