### ISSUE TITLE
Regulus Theme weather icon showing box

### ISSUE THREAD

**Issue by bmcdougald** [closebox73/applying-theme#2]
First off love the theme work.  I got everything working on it except the weather icons.  I downloaded the weather-icons from the erikflowers site, loaded them on the system and also dropped them in the fonts folder under ~/.config/conky/Regulus/fonts.  Still shows as a box.  I looked at the weather-text-icon file and the variables have various asian characters in the quotes.  I'm not sure if that's what's breaking this since I have an English system that may not be able to show asian character fonts.  Still not sure how those get converted to clouds or sun images.

**Comment by bmcdougald** [comment]
Nevermind... looks like it's not using the erikflowers fonts as commented in the config...it's using feather font for that graphic.  Problem solved.

**Comment by closebox73** [comment]
ah.. I'm sorry it's my fault
The font that should be used is Feather icon font.. I will Update it
