### ISSUE TITLE
Unable to show Spotify info

### ISSUE THREAD

**Issue by OckhamOdyssey** [closebox73/applying-theme#6]
Hi, I just bought your Mimosa theme, I really like the style, fits perfectly with my DE and you have done a very great job creating themes. I used mpd some time ago without good experiences. I mainly use Spotify client or the browser player (Spotify again, YouTube...). Can MPD be used for Spotify? If not, can your themes support it?

Thanks for your job :)

**Comment by closebox73** [comment]
actually I don't use spotify😆, but I can display that info on Mimosa.. I'll try to summarize the method, please wait

**Comment by closebox73** [comment]
the most concise method is to use **playerctl** ,
can be used for many media players, please install it fisrt
then open Mimosa.conf in text editor
go to line 94 and replace `mpd_artist` with
`exec playerctl metadata xesam:artist`

and line 95 replace `mpd_title` with
`exec playerctl metadata xesam:title`

see documentation of playerctl [Here](https://github.com/altdesktop/playerctl)

**Comment by closebox73** [comment]
for example 

![Scrot_22 12 21_21 30 29](https://user-images.githubusercontent.com/91961267/208929109-17fc96e4-31df-47c4-b184-843f0dbdf824.png)

**Comment by OckhamOdyssey** [comment]
Looks promising. I change the config and looks good, I will test it in a few hours to confirm.

**Comment by OckhamOdyssey** [comment]
Yup, now shows everything, but sometimes, something disappear. Here are some examples.
![image](https://user-images.githubusercontent.com/60941836/208998145-f668733e-c5c9-4445-a1d7-7f1ce880db55.png)
![image](https://user-images.githubusercontent.com/60941836/208998182-ef3daf62-f7d4-4e68-b075-cf5f8289ba46.png)
![image](https://user-images.githubusercontent.com/60941836/208998216-83b43989-57d5-4c8a-b0b7-9653294b5b3d.png)

Here is the last part of the code. I just change this lines and the titles to Spanish.

```
${color}${offset 172}${voffset -105}${if_running mpd}${font Material:size=18}
${color}${offset 172}${voffset 0}${font Abel:size=9}${exec playerctl status}
${color2}${offset 172}${voffset 0}${font Abel:bold:size=10}${exec playerctl metadata xesam:artist}${font}
${color}${offset 172}${voffset 0}${font Abel:italic:size=9}${exec playerctl metadata xesam:title}${font}
${color}${offset 172}${voffset 0}${font Abel:size=8}${exec playerctl position --format "{{ duration(position) }}"}${font}
]]
```

If you want all the code… I suppose you don't want it here, as it is only available on Ko-Fi.

The logs also reference errors on file `scripts/weather-text-icon` but I didn't touch it.

**Comment by OckhamOdyssey** [comment]
Ok, with Spotify in the browser works fine, really fine. So the problem looks like the Spotify client, I have it installed with flatpak, let me uninstall it and try again with the AUR version.

**Comment by OckhamOdyssey** [comment]
I tried the AUR version, and it has other problems. Everything is smooth but the status and the position cannot be detected by `playerctl`. Obviously AUR is unsupported, we should try a Debian-based system, but I have none.

Still a great option as it works perfectly on the browser, even YouTube videos. My issue is solved, but I still receive the next error:
`conky: llua_do_call: function conky_ring_stats execution failed: attempt to call a nil value`

Is this causing the circle graphics not to show? The next screenshot is from a fresh installation of Mimosa. Do you want me to open this issue in your Leonis repo?
![image](https://user-images.githubusercontent.com/60941836/209010003-feb56a9d-1d7e-4236-a2dd-fef015289d4b.png)

**Comment by closebox73** [comment]
one of the reasons to only use mpd is that if you use a command that can handle a lot of media, there will definitely be a lot of issues. For problems with Lua scripts, sometimes different distros must have problems related to libraries or something like that.

if I'm not mistaken, it was resolved by installing **conky_lua**.
but if you want to open this issue, go ahead, maybe someone can help

**Comment by OckhamOdyssey** [comment]
Yup. That also worked. TYSM
