### ISSUE TITLE
Does not work on Gnome 41 in Ubuntu

### ISSUE THREAD

**Issue by Jasdent** [closebox73/applying-theme#9]
![image](https://github.com/closebox73/applying-theme/assets/33674169/acfaa45c-bea3-4798-9a1e-7323dad2570d)

GNOME 41.7
I followed the instruction to set `own_window_argb_visual = true`

**Comment by closebox73** [comment]
@Jasdent indeed for gnome this kind of problem always appears, it seems I also have to use gnome so I can get the solution😣

**Comment by cristimc8** [comment]
I have found a possible solution for Gnome transparency bugs, make sure to follow [this topic](https://bbs.archlinux.org/viewtopic.php?id=246770) and add 
```
draw_blended = false
own_window_argb_visual = true
own_window_transparent = false
```

For me, on Gnome 44.3 it's rendering alright
![image](https://github.com/closebox73/applying-theme/assets/14197491/fb40677d-c860-40e1-bdda-1904d793b142)

**Comment by closebox73** [comment]
Hi @cristimc8 Thank you, I will recommend it to others if this happens.
